# Generated by Django 2.1.3 on 2019-03-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190310_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registers',
            name='email',
            field=models.EmailField(max_length=200, unique=True),
        ),
    ]
